############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1


[[main]]
name = "Events"
url = "/events"
weight = 2

[[main]]
weight = 3
name = "Pages"

[[main]]
parent = "Pages"
name = "Blog"
url = "/blog"

[[main]]
parent = "Pages"
name = "Contact"
url = "/contact"


[[main]]
parent = "Pages"
name = "Our Sponsers"
url = "/our-sponsers"

[[main]]
weight = 4
name = "Speakers"
url = "/speakers"

[[main]]
name = "Get Tickets"
url = "/get-tickets"
weight = 5

# footer menu

[[footer_menu_quick_links]]
name = "Home"
url = "/"
weight = 1

[[footer_menu_quick_links]]
name = "About The Event"
url = "/events"
weight = 2

[[footer_menu_quick_links]]
name = "Speakers"
url = "/speakers"
weight = 3

[[footer_menu_quick_links]]
name = "Workshop Sessions"
url = "/events"
weight = 4

[[footer_menu_quick_links]]
name = "Sponsor Partners"
url = "/our-sponsers"
weight = 5


[[footer_menu_get_started]]
name = "Register Now"
url = "/events"
weight = 1

[[footer_menu_get_started]]
name = "Get Tickets"
url = "/get-tickets"
weight = 2

[[footer_menu_get_started]]
name = "Our Gallery"
url = "/our-gallery"
weight = 3

[[footer_menu_get_started]]
name = "Stay in the loop"
url = "#"
weight = 4

[[footer_menu_get_started]]
name = "Terms of service"
url = "/terms-of-service"
weight = 5