############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1


[[main]]
name = "Events"
url = "/events"
weight = 2

[[main]]
weight = 3
name = "Pages"

[[main]]
parent = "Pages"
name = "Blog"
url = "/blog"

[[main]]
parent = "Pages"
name = "Contact"
url = "/contact"


[[main]]
parent = "Pages"
name = "Our Sponsers"
url = "/our-sponsers"

[[main]]
weight = 4
name = "Speakers"
url = "/speakers"

[[main]]
name = "Get Tickets"
url = "/get-tickets"
weight = 5

# footer menu
[[footer]]
name = "Get Tickets"
url = "/get-tickets"
weight = 1

[[footer]]
name = "Elements"
url = "/elements"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 3
